// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208080443_FixSeedDataIsDisabled")]
    partial class FixSeedDataIsDisabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Domain.Aggregations.Decommissioning", b =>
                {
                    b.Property<int>("DecommissioningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DecommissioningDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DecommissioningRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalDestination")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DecommissioningId");

                    b.ToTable("Decommissionings");
                });

            modelBuilder.Entity("Domain.Aggregations.DecommissioningRequest", b =>
                {
                    b.Property<int>("DecommissioningRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DecommissioningRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("DecommissioningRequests");
                });

            modelBuilder.Entity("Domain.Aggregations.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaintenanceRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Mainteinances");
                });

            modelBuilder.Entity("Domain.Aggregations.ReceivingInspectionRequest", b =>
                {
                    b.Property<int>("ReceivingInspectionRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceivingInspectionRequestId");

                    b.ToTable("ReceivingInspectionRequests");
                });

            modelBuilder.Entity("Domain.Aggregations.Rejection", b =>
                {
                    b.Property<int>("RejectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DecommissioningRequestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RejectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RejectionId");

                    b.ToTable("Rejections");
                });

            modelBuilder.Entity("Domain.Aggregations.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransferId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentId");

                    b.HasIndex("SectionId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            IsDisabled = false,
                            Name = "Almacen General",
                            SectionId = -1
                        },
                        new
                        {
                            DepartmentId = -1,
                            IsDisabled = false,
                            Name = "Conmutación y Enrutamiento Avanzado",
                            SectionId = -1
                        },
                        new
                        {
                            DepartmentId = -2,
                            IsDisabled = false,
                            Name = "Seguridad Perimetral y Firewalls",
                            SectionId = -1
                        },
                        new
                        {
                            DepartmentId = -3,
                            IsDisabled = false,
                            Name = "Reparaciones de Red",
                            SectionId = -1
                        },
                        new
                        {
                            DepartmentId = -4,
                            IsDisabled = false,
                            Name = "Servidores y Virtualización",
                            SectionId = -2
                        },
                        new
                        {
                            DepartmentId = -5,
                            IsDisabled = false,
                            Name = "Almacenamiento y Backup",
                            SectionId = -2
                        },
                        new
                        {
                            DepartmentId = -6,
                            IsDisabled = false,
                            Name = "Infraestructura Física y Climatización",
                            SectionId = -2
                        },
                        new
                        {
                            DepartmentId = -7,
                            IsDisabled = false,
                            Name = "Instalaciones y Activaciones",
                            SectionId = -3
                        },
                        new
                        {
                            DepartmentId = -8,
                            IsDisabled = false,
                            Name = "Mantenimiento Correctivo y Urgencias",
                            SectionId = -3
                        },
                        new
                        {
                            DepartmentId = -9,
                            IsDisabled = false,
                            Name = "Soporte a Nodos Remotos",
                            SectionId = -3
                        },
                        new
                        {
                            DepartmentId = -10,
                            IsDisabled = false,
                            Name = "Diseño y Ingeniería de Red",
                            SectionId = -4
                        },
                        new
                        {
                            DepartmentId = -11,
                            IsDisabled = false,
                            Name = "Despliegue de Fibra Óptica y Acceso",
                            SectionId = -4
                        },
                        new
                        {
                            DepartmentId = -12,
                            IsDisabled = false,
                            Name = "Mediciones y Certificación de Red",
                            SectionId = -4
                        },
                        new
                        {
                            DepartmentId = -13,
                            IsDisabled = false,
                            Name = "Infraestructura como Servicio",
                            SectionId = -5
                        },
                        new
                        {
                            DepartmentId = -14,
                            IsDisabled = false,
                            Name = "Plataforma como Servicio",
                            SectionId = -5
                        },
                        new
                        {
                            DepartmentId = -15,
                            IsDisabled = false,
                            Name = "Operaciones Cloud y Escalabilidad",
                            SectionId = -5
                        },
                        new
                        {
                            DepartmentId = -16,
                            IsDisabled = false,
                            Name = "Recepción y Diagnóstico Técnico",
                            SectionId = -6
                        },
                        new
                        {
                            DepartmentId = -17,
                            IsDisabled = false,
                            Name = "Reparación y Refabricación",
                            SectionId = -6
                        },
                        new
                        {
                            DepartmentId = -18,
                            IsDisabled = false,
                            Name = "Gestión de Inventario y Distribución",
                            SectionId = -6
                        },
                        new
                        {
                            DepartmentId = -19,
                            IsDisabled = false,
                            Name = "Soporte al Usuario y Helpdesk",
                            SectionId = -7
                        },
                        new
                        {
                            DepartmentId = -20,
                            IsDisabled = false,
                            Name = "Comunicaciones Unificadas y Telefonía IP",
                            SectionId = -7
                        },
                        new
                        {
                            DepartmentId = -21,
                            IsDisabled = false,
                            Name = "Gestión de Activos y Red Local",
                            SectionId = -7
                        },
                        new
                        {
                            DepartmentId = -22,
                            IsDisabled = false,
                            Name = "Arquitectura y Gestión de Firewalls",
                            SectionId = -8
                        },
                        new
                        {
                            DepartmentId = -23,
                            IsDisabled = false,
                            Name = "Monitorización de Amenazas y SOC",
                            SectionId = -8
                        },
                        new
                        {
                            DepartmentId = -24,
                            IsDisabled = false,
                            Name = "Análisis Forense y Respuesta a Incidentes",
                            SectionId = -8
                        });
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationalState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceId = -1,
                            AcquisitionDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -8,
                            IsDisabled = false,
                            Name = "Router de Agregación ASR 9000",
                            OperationalState = 2,
                            Type = 0
                        },
                        new
                        {
                            DeviceId = -2,
                            AcquisitionDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -16,
                            IsDisabled = false,
                            Name = "Servidor de Virtualización HP DL380",
                            OperationalState = 3,
                            Type = 1
                        },
                        new
                        {
                            DeviceId = -3,
                            AcquisitionDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -24,
                            IsDisabled = false,
                            Name = "Firewall de Próxima Generación PA-5200",
                            OperationalState = 2,
                            Type = 0
                        },
                        new
                        {
                            DeviceId = -4,
                            AcquisitionDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -24,
                            IsDisabled = false,
                            Name = "Sistema UPS Eaton 20kVA",
                            OperationalState = 4,
                            Type = 2
                        },
                        new
                        {
                            DeviceId = -5,
                            AcquisitionDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -12,
                            IsDisabled = false,
                            Name = "Antena de Radioenlace AirFiber 5XHD",
                            OperationalState = 2,
                            Type = 3
                        },
                        new
                        {
                            DeviceId = -6,
                            AcquisitionDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -14,
                            IsDisabled = false,
                            Name = "Analizador de Espectro Viavi",
                            OperationalState = 2,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.PerformanceRating", b =>
                {
                    b.Property<int>("PerformanceRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceRatingId");

                    b.HasIndex("UserId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Technician"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "EquipmentReceiver"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "SectionManager"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Director"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Logistician"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SectionManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SectionId");

                    b.HasIndex("SectionManagerId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = -1,
                            IsDisabled = false,
                            Name = "Operaciones de Red Corporativa"
                        },
                        new
                        {
                            SectionId = -2,
                            IsDisabled = false,
                            Name = "Infraestructura de Centro de Datos (Data Center)"
                        },
                        new
                        {
                            SectionId = -3,
                            IsDisabled = false,
                            Name = "Soporte Técnico en Campo"
                        },
                        new
                        {
                            SectionId = -4,
                            IsDisabled = false,
                            Name = "Planificación y Despliegue de Red"
                        },
                        new
                        {
                            SectionId = -5,
                            IsDisabled = false,
                            Name = "División de Servicios en la Nube (Cloud)"
                        },
                        new
                        {
                            SectionId = -6,
                            IsDisabled = false,
                            Name = "Taller Central y Logística"
                        },
                        new
                        {
                            SectionId = -7,
                            IsDisabled = false,
                            Name = "Infraestructura Interna (TI Interno)"
                        },
                        new
                        {
                            SectionId = -8,
                            IsDisabled = false,
                            Name = "Seguridad Informática (Ciberseguridad)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = -1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -21,
                            FullName = "David González",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkxPo0Sl6gHf46gy7Pe5xeZZa0X2gGboRBG4Rd9gWniOm1PGHZ7he",
                            RoleId = 4,
                            Username = "dgonzalez"
                        },
                        new
                        {
                            UserId = -2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -18,
                            FullName = "Laura Martínez",
                            IsActive = true,
                            PasswordHash = "$2a$11$2u/fqdnoGBupkujZw8HXeu3tjULZ6e.EqZVEQwLmWGWRvPPpu8gee",
                            RoleId = 4,
                            Username = "lmartinez"
                        },
                        new
                        {
                            UserId = -3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -18,
                            FullName = "Javier Rodríguez",
                            IsActive = true,
                            PasswordHash = "$2a$11$/jwi2T7PHM6fSAyAelnoaOOxPMLU25uXG/3NvTyTK5rMlEoSZm55y",
                            RoleId = 4,
                            Username = "jrodriguez"
                        },
                        new
                        {
                            UserId = -4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -5,
                            FullName = "Carmen Sánchez",
                            IsActive = true,
                            PasswordHash = "$2a$11$J0ZStMp50aiYljT3vj.yQucG.tqZOI7x43quH5EdmzB6K5z5cIVuq",
                            RoleId = 4,
                            Username = "csanchez"
                        },
                        new
                        {
                            UserId = -5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -3,
                            FullName = "Roberto López",
                            IsActive = true,
                            PasswordHash = "$2a$11$OlHPfN0V9EcZwDZ2NhvzaOT0E6F8/EfWo2wHzJhSFEVEwd7fqBkCa",
                            RoleId = 4,
                            Username = "rlopez"
                        },
                        new
                        {
                            UserId = -6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -24,
                            FullName = "Elena Morales",
                            IsActive = true,
                            PasswordHash = "$2a$11$frxc8XpGXgGi53fiLcSRoOt3Nq7aE56VMPf.ECnNWXJkxIFPXxrMq",
                            RoleId = 5,
                            Username = "emorales"
                        },
                        new
                        {
                            UserId = -7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -1,
                            FullName = "Sofía Ramírez",
                            IsActive = true,
                            PasswordHash = "$2a$11$eZJoOAWDoV6iLxXJtV3sjeW134dzJnATrW0BUXedvDUpm8D3v1vC6",
                            RoleId = 3,
                            Username = "sramirez"
                        },
                        new
                        {
                            UserId = -8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -6,
                            FullName = "Alejandro Torres",
                            IsActive = true,
                            PasswordHash = "$2a$11$2p2NYJ3apLI342Dtp5EpEub2nxcPFkzsb88ci3oDI25IykC.0Unfm",
                            RoleId = 3,
                            Username = "atorres"
                        },
                        new
                        {
                            UserId = -9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -7,
                            FullName = "Patricia Herrera",
                            IsActive = true,
                            PasswordHash = "$2a$11$ZeaAzBiPv.Xw6IYn5HsfM.TsEo8Rsh7iwC6xyVRAY6kAibSVuK.IW",
                            RoleId = 3,
                            Username = "pherrera"
                        },
                        new
                        {
                            UserId = -10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -10,
                            FullName = "Ricardo Díaz",
                            IsActive = true,
                            PasswordHash = "$2a$11$DuHpt0qFrD1nX4vvR6ypUu59ou5tGK8J.v8k3KhzMCQ/LzqyFOfWi",
                            RoleId = 3,
                            Username = "rdiaz"
                        },
                        new
                        {
                            UserId = -11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -13,
                            FullName = "Isabel Castro",
                            IsActive = true,
                            PasswordHash = "$2a$11$6l3KjoYoKF0fDqIgEDwB4u8gUJ6IKOQgMf1K6n4DoYneSFqPrMRvu",
                            RoleId = 3,
                            Username = "icastro"
                        },
                        new
                        {
                            UserId = -12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -3,
                            FullName = "Carlos Méndez",
                            IsActive = true,
                            PasswordHash = "tech01",
                            RoleId = 1,
                            Specialty = "Redes y Comunicaciones",
                            Username = "cmendez",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            UserId = -13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -6,
                            FullName = "Eduardo Vargas",
                            IsActive = true,
                            PasswordHash = "tech02",
                            RoleId = 1,
                            Specialty = "Servidores y Virtualización",
                            Username = "evargas",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            UserId = -14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -9,
                            FullName = "Jorge Silva",
                            IsActive = true,
                            PasswordHash = "tech03",
                            RoleId = 1,
                            Specialty = "Electricidad y Energía",
                            Username = "jsilva",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            UserId = -15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -22,
                            FullName = "María Ortega",
                            IsActive = true,
                            PasswordHash = "tech04",
                            RoleId = 1,
                            Specialty = "Ciberseguridad",
                            Username = "mortega",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            UserId = -16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -11,
                            FullName = "Ana López",
                            IsActive = true,
                            PasswordHash = "tech05",
                            RoleId = 1,
                            Specialty = "Fibra Óptica",
                            Username = "alopez",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            UserId = -17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -9,
                            FullName = "Miguel Ángel Santos",
                            IsActive = true,
                            PasswordHash = "rec01",
                            RoleId = 2,
                            Username = "msantos"
                        },
                        new
                        {
                            UserId = -18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -2,
                            FullName = "Ana García",
                            IsActive = true,
                            PasswordHash = "rec02",
                            RoleId = 2,
                            Username = "agarcia"
                        },
                        new
                        {
                            UserId = -19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -6,
                            FullName = "Luis Fernández",
                            IsActive = true,
                            PasswordHash = "rec03",
                            RoleId = 2,
                            Username = "lfernandez"
                        },
                        new
                        {
                            UserId = -20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -24,
                            FullName = "Marta Jiménez",
                            IsActive = true,
                            PasswordHash = "rec04",
                            RoleId = 2,
                            Username = "mjimenez"
                        },
                        new
                        {
                            UserId = -21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = -17,
                            FullName = "Carlos Ruiz",
                            IsActive = true,
                            PasswordHash = "rec05",
                            RoleId = 2,
                            Username = "cruiz"
                        });
                });

            modelBuilder.Entity("Domain.Aggregations.DecommissioningRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("DecommissioningsProposed")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.Aggregations.MaintenanceRecord", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("MaintenancesPerformed")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.HasOne("Domain.Entities.Department", null)
                        .WithMany("Device")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PerformanceRating", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Section", b =>
                {
                    b.HasOne("Domain.Entities.User", "SectionManager")
                        .WithMany()
                        .HasForeignKey("SectionManagerId");

                    b.Navigation("SectionManager");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Device");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("DecommissioningsProposed");

                    b.Navigation("MaintenancesPerformed");

                    b.Navigation("PerformanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
